# Generated by Django 5.1.2 on 2024-10-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_Store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('biscuits', 'Печенье'), ('milk', 'Молочные'), ('bread', 'Хлебные')], default='biscuits', max_length=10, verbose_name='Категория'),
        ),
    ]
